# Rime schema
# encoding: utf-8

__include: cangjie5.schema:/

schema:
  schema_id: cangjie5_simp
  name: 倉頡五代·简化字
  dependencies:
    - pinyin_simp

switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - options: [zh_hant, zh_hans, zh_hant_tw]
    reset: 1
    states: [傳統漢字, 简化字, 臺灣字形]
  - name: extended_charset
    states: [ 常用, 增廣 ]
  - name: ascii_punct
    states: [ 。，, ．， ]

translator:
  dictionary: cangjie5_simp

reverse_lookup:
  dictionary: pinyin_simp
  prism: pinyin_simp

zh_hant:
  opencc_config: s2t.json
  option_name: zh_hant
  tips: all

zh_hant_tw:
  opencc_config: s2tw.json
  option_name: zh_hant_tw
  tips: all
