patch:
  schema_list:
    - schema: cangjie5
    - schema: cangjie5_simp
    - schema: double_pinyin_flypy
    - schema: double_pinyin_flypy_simp
    - schema: japanese_kana
  "key_binder/bindings/+":
    - { when: always, accept: "Shift+space", toggle: noop }
